### ISSUE TITLE
[DOCS] Add my Nix Flake to the documentation?

### ISSUE THREAD

**Issue by jiriks74** [aclist/dztui#167] opened 2024-11-24 03:40 UTC
Hello,
haven't been here for a while since I haven't playd DayZ for quite some time.

I've since switched to NixOS and oh my that OS is a challenge XD.

To run `dzgui` on NixOS I had to make some patches (basically disabling self updates, branch switching and fixing the `ping` command arguments) to this project and wrap it in a way that allows it to run properly.
And now I'm proud to announce that I've succeeded in this effort!

Since making this run isn't trivial and there aren't any DayZ launchers available (one is in `unstable` but it's proprietary and is broken as of now) I'd like to make this more public so that more people can run DayZ on NixOS without too much hassle.

I thought that adding it to `dzgui` wiki would be the right place to do so - with a big **!** that this is community maintained and **you are not** responsible for any problems or breakages and **you will not** be fixing anything if it's broken. Just send people to my project's issues instead.

I'd like to know what you think about this.

---

[Here's the project](https://github.com/jiriks74/dzgui.flake).

Most of the modifications can be found in the `patches/` directory but some variables containing paths had to be modified in the `flake.nix` file.

**What I've tested:**
- Server browser
- My saved servers
- Automatic install mode
- Listing installed mods
- Launching DayZ and connecting to a server
Possibly others. (I haven't found anything that's not working).

> [!Note]
> I didn't upstream this to `nixpkgs` as `dzgui` gets sometimes updates quite often to fix stuff. Updating every few weeks would be an annoying and a slow process and it could even misrepresent the state of this project (broken launcher while a fix was pushed 2 weeks ago).

**PS:**
Last time I played DayZ `dzgui` installed mods by launching Steam with the dev console opened, then it focused the window and started pasting from the clipboard to it. It could break easily but it was so much better than downloading hundreds of mods.
When I ran `dzgui` again I was really pleasantly surprised when this didn't happen and you instead found a better approach.

I'm glad to see your project doing so well! It's nice to see these *smaller* projects holding up and getting better!

**Comment by aclist** [comment] 2024-11-24 14:39
> Hello, haven't been here for a while since I haven't playd DayZ for quite some time.

Thanks for your message and for your help in the past.

> To run `dzgui` on NixOS I had to make some patches (basically disabling self updates, branch switching and fixing the `ping` command arguments) to this project and wrap it in a way that allows it to run properly. And now I'm proud to announce that I've succeeded in this effort!

Great job. Another user actually attempted to do this; it's listed near the top of the DZGUI documentation. You can find it here: https://github.com/lelgenio/dzgui-nix. I don't know too much about it, but it seems to be in synch with at least the stable branch releases. Maybe you can blend both of your ideas and see if there are some improvements you can mutually benefit from? It seems like the other user added a series of patches as well. I thought it was interesting that you are providing turnkey access to both branches.

> Since making this run isn't trivial and there aren't any DayZ launchers available (one is in `unstable` but it's proprietary and is broken as of now) I'd like to make this more public so that more people can run DayZ on NixOS without too much hassle.

Anything I can do to help here? With regard to release cadence, packaging approach, something else? DZGUI stable is on a much more leisurely release cadence now, and I'm only bumping the minor or major version after there are significant new features to port over from testing. However, stable does still get the occasional hotfix if it's important. Currently the `main` branch of DZGUI is kind of for archival purposes and just gets the contents of the `dzgui` (stable) branch cloned into it occasionally after version bumps. I might rearrange this in the future, but haven't decided yet. Testing is still more of the "DZGUI labs" branch, but a fair amount of users use it as their main branch since they want the newer features. And testing is relatively stable as well, it is more of a soft release area for new features, nowhere near as volatile as it once was.

> I thought that adding it to `dzgui` wiki would be the right place to do so - with a big **!** that this is community maintained and **you are not** responsible for any problems or breakages and **you will not** be fixing anything if it's broken. Just send people to my project's issues instead.

I agree that it should be out of my hands. With the other nix flake, it was suggested that it be bundled with DZGUI's source code, but this didn't seem like the right approach to me from a maintainability perspective, so I suggested linking it from the docs.

> **What I've tested:**

There are a number of significant new features on `testing` that you might not have seen:

- Options > List installed mods panel
    - You can now bulk select/deselect mods and bulk delete them. (This is mainly relevant to auto mod install mode). This should work fine provided you didn't manually subscribe to mods in Steam workshop. 
    - You can use the `Highlight stale` button to walk through your list of saved servers, check their modlists, and highlight any local mods you have installed that are not needed on any of those servers. Those will be highlighted in red as "safe to delete". Obviously this comes with some caveats, see #162. I'm probably going to rename this button to something less vague, but the functionality should be the same.
- Overall improvements to how the window header behaves and displays contexts when you go to different menus

> **PS:** Last time I played DayZ `dzgui` installed mods by launching Steam with the dev console opened, then it focused the window and started pasting from the clipboard to it. It could break easily but it was so much better than downloading hundreds of mods. When I ran `dzgui` again I was really pleasantly surprised when this didn't happen and you instead found a better approach.

Yes, I agree. Much better now. I'm constantly trying to refine these pain points and incorporate what users ask for, even if it's tricky to implement at times. DZGUI today is so different from the DZGUI of three years ago; it's a Ship of Theseus now, where it feels like we've replaced every part one by one. If there's something else you feel is lacking, please let me know. We have a lot of generic widgets and components built up that we can recycle to create different menus now, so it's a bit easier to prototype new UI elements than before.

Also, thanks for making me aware of the special Markdown tags on GH, I didn't know about those until now. Definitely adds clarity and I will be using those in the future.

> I'm glad to see your project doing so well! It's nice to see these _smaller_ projects holding up and getting better!

I'll continue supporting the project indefinitely. I believe it's the most feature complete and actively maintained tool of its kind. Next year I want to tackle a rewrite of the setup menus and create more of a smooth setup wizard, because I know that new users get frustrated by the setup process at times (having to add lots of keys and stuff). I'm trying to add enough features so that power users can do what they want, but I don't want users with basic needs to be left in the cold, either. And Steam Deck users (of which there are a lot) demand the most simple, plug-and-play setup.

**Comment by jiriks74** [comment] 2024-11-24 19:32
> Maybe you can blend both of your ideas and see if there are some improvements you can mutually benefit from?

I've had a quick look at it and I'll for sure be doing some improvements to mine. Some things I did are a bit overkill so I'll be fixing that and I'll be working on the integration, as that's what I'm missing RN.

> Anything I can do to help here? With regard to release cadence, packaging approach, something else?

I'm not sure. It seems that the launcher isn't as unstable (or rather unreliable) as it was in previous years and the updates to the `dzgui` branch aren't as frequent as they were at that time. Now that I look at it I could look into getting the stable version upstream but I wouldn't do it with the testing branch.

> With the other nix flake, it was suggested that it be bundled with DZGUI's source code

I thought about that too but this doesn't burden you and it's easier to fix if something breaks as it doesn't have to go through a PR. Also it's way more clear that this is *community support* and not *official support*.

> You can now bulk select/deselect mods and bulk delete them

That sounds epic! It crossed my mind how I'll be deleting mods if `dzgui` manages them but I now play on one server so I didn't look into it closer. With this the mod management is basically feature complete as you can both install and delete.

> Also, thanks for making me aware of the special Markdown tags on GH, I didn't know about those until now. Definitely adds clarity and I will be using those in the future.

I've kinda found it by accident. It's called markdown admonitions and AFIK it's not standard and everyone does it differently. I think I found out that Github supports it through this discussion: https://github.com/orgs/community/discussions/16925

> I believe it's the most feature complete and actively maintained tool of its kind.

Totally agree.

> Next year I want to tackle a rewrite of the setup menus and create more of a smooth setup wizard, because I know that new users get frustrated by the setup process at times (having to add lots of keys and stuff). I'm trying to add enough features so that power users can do what they want, but I don't want users with basic needs to be left in the cold, either. And Steam Deck users (of which there are a lot) demand the most simple, plug-and-play setup.

I find the setup quite easy but it makes sense that people who are not developers might have some issues understanding how to get the API keys. Better plug-and-play setup will be appreciated by everyone I think.

> I'll continue supporting the project indefinitely.

That's great to hear! I wish you the best with this project as it for sure took a lot of work and it shows.

**Comment by aclist** [comment] 2024-11-25 10:10
> I'm not sure. It seems that the launcher isn't as unstable (or rather unreliable) as it was in previous years and the updates to the `dzgui` branch aren't as frequent as they were at that time. Now that I look at it I could look into getting the stable version upstream but I wouldn't do it with the testing branch.

One of the main reasons DZGUI doesn't use makefiles or static packages is because it also has to work OOTB on Steam Deck, where users have reduced privileges on most stock setups, and sudo isn't even configured by default. Also, DayZ is frequently changing or breaking things, so it's not a good idea to run an old version; DZGUI should basically be on the latest version at all times to maintain correct functionality. I may change my mind about this in the future, but this feels like the best compromise for most users. And people tended to use old versions and report bugs that were already fixed.

I guess the way Steam and other "over-the-air" applications do it is they don't even let you reject software updates for maximum compatibility. DZGUI at least offers the option to refuse to update when prompted to do so.

A lot of the things that DZGUI does that may seem unorthodox are for the convenience of Steam Deck users.

> I thought about that too but this doesn't burden you and it's easier to fix if something breaks as it doesn't have to go through a PR. Also it's way more clear that this is _community support_ and not _official support_.

Next time I spruce up the documentation (soon), I'll definitely add a link to your repository with some disclaimers.

> That sounds epic! It crossed my mind how I'll be deleting mods if `dzgui` manages them but I now play on one server so I didn't look into it closer. With this the mod management is basically feature complete as you can both install and delete.

The only thing that can be problematic is if the user has been using manual mod subscriptions on Steam Workshop for some time before switching to auto mode. The mods are still considered "subscribed" to on Steam, so they might get auto updates force pushed by Steam  if the user deletes the mod folder itself. There's no programmatic way of unsubscribing you from mods here, so I'll have to add an admonition to users toggling from Manual -> Auto to check their Workshop subscriptions to make sure there aren't any leftover mods. 

I'm going to keep this ticket open until I update the docs.

**Comment by jiriks74** [comment] 2024-11-27 21:12
Hello again.

I've come across an issue with the testing branch. I'm not sure that it's 100% `dzgui`'s problem so I'll kindly ask you to reproduce this until I make a separate issue.

When I try to list installed mods on the `testing` branch I get this:

<details>
<summary>Screenshot</summary>

![Screenshot_20241127_220414](https://github.com/user-attachments/assets/3df4ca10-771d-482b-a6df-b61e856ee83e)

</details>

Instead of the list being populated. I've tried running `dzgui` directly (not my packaged version) in a FHS environment (aka what other Linux distributions' filesystem looks like) and I got the same outcome. Since `dzgui` has the same problem without any modifications I think its not an issue with my package but I still want to be sure before making a new issue.

Could you please try to reproduce it @aclist?

**Comment by aclist** [comment] 2024-11-28 07:41
It's almost certainly related to some internal changes to the UI code, but I couldn't reproduce it yet. Can you run the app up till you get this issue, then quit, and send your `DZGUI_DEBUG.log` (`$HOME/.local/state/DZGUI_DEBUG.log`) as a text attachment?

**Comment by aclist** [comment] 2024-11-28 08:13
It looks like there was a race condition. Making a few changes to the testing branch and will update when it's done.

**Comment by aclist** [comment] 2024-11-28 08:44
Please give it a try now.

**Comment by jiriks74** [comment] 2024-11-28 11:19
It's still happening for me both on my laptop and my pc. I'll be opening a new issue and I'll be getting the logs for you. I'll be able to do so in cca 2 hours.

THX for the quick response!

**Comment by aclist** [comment] 2024-11-28 14:12
Also perform these steps:

- Navigate to `$HOME/.local/share/dzgui/helpers`
- Invoke `./funcs "List installed mods" > mymods`
- Save the below to `test.py`

```Python
import csv
import locale
import sys
import traceback

delimiter="␞"

def parse_mod_rows(file):
    sum = 0
    with open(file, "r") as infile:
        lines = [line.rstrip() for line in infile]
    hits = len(lines)
    reader = csv.reader(lines, delimiter=delimiter)
    try:
        rows = [[row[0], row[1], row[2], locale.atof(row[3], func=float), None] for row in reader if row]
    except (IndexError, ValueError):
        print(traceback.format_exc())
        return 1
    for row in rows:
        size = float(row[3])
        sum += size
    print([sum, hits])

if len(sys.argv) < 2:
    print("Supply a filename as argument")
    sys.exit(1)
parse_mod_rows(sys.argv[1])
```

- Invoke `python3 test.py mymods`
- If the output is clean, it should print the total mod size and number of mods. If the data is malformed, post the traceback

**Comment by aclist** [comment] 2024-12-13 02:05
Closing as resolved. Added link to fork here: https://aclist.codeberg.page/installation.html#nixos-installation

Let me know if this should be worded differently.

**Closed by aclist** 2024-12-13 02:05 UTC
Labels: documentation
