### ISSUE TITLE
DZG tries to download mods that do not exist

### ISSUE THREAD

**Issue by KewDok** [aclist/dztui#155] opened 2024-10-04 06:35 UTC
I play on DayZ server `MAG MiddeAgedGamers #1 PVE`. 
IP 5.252.100.201:2303
When attempting to launch from DZG on my Steam Deck it tries to open Workshop pages that do not exist, and I can't find a way around it.

How to recreate:  Launch the server. DZG will try to add mods that do not exist. One example it tries to download is workshop item 1396978764. This is not a mod (at least not currently).
![Screenshot_20241004_143350](https://github.com/user-attachments/assets/d2b3e91e-f294-482c-a9f2-6f2a8612a654)

Hopefully this is something that you will find time to look into. Thanks for an awesome tool!

**Comment by aclist** [comment] 2024-10-04 07:18
Please provide the following information:

- DZGUI version
- Stable or Testing branch
- Mod dowload mode set in Options menu (Manual or Auto)

**Comment by aclist** [comment] 2024-10-04 12:27
I have checked, and this is not a mod ID being returned by the server at any point in the DZGUI pipeline. The only possibility is that this is a mod you had previously downloaded from another server, and DZGUI has determined that it needs to be updated. (But the mod is defunct now.) Can you check for the presence of the file `$HOME/.local/state/dzgui/dzg.versions` and rename or remove this file, then see if this stops the download from being triggered?

**Comment by KewDok** [comment] 2024-10-05 03:57
You are right. After unsubscribing from all mods on steampowered.com (browser, not the Steam client, just in case there is a sync issue) I was able to use DZGUI to verify mods and access the modded server. 
Just a comment from me: If possible, you might look into changing DZGUI behaviour from verifying all mods when accessing a server to only verifying mods that are actually active and in use on that particular server. 

Thanks for the quick follow-up and keep up the good work! :-)

**Comment by aclist** [comment] 2024-10-05 16:14
Thank you very much for your support. I am aware that this is a design flaw and I am considering how best to improve it without negatively affecting other workflows. Giving a very simple summary, when using Auto download mode, we need to keep track of the signatures of other mods because automatic downloads are delegated to DZGUI. The problem is that once the user switches back to Manual download mode, this behavior should be automatically disabled.

Secondly, there is a redundancy check in place to make sure mods are not defunct on Steam, but in this particular scenario, it looks like it wasn't being applied properly, so I am investigating the root cause.

**Comment by aclist** [comment] 2024-10-05 17:51
@KewDok 

Please disregard the initial comments above. I have done a root cause analysis and was able to reproduce your issue. It is not being caused by DZGUI's mod sync method. As for the cause, this is a tricky one. A summary follows:

Using DZGUI's internal server query method, the mod id `1396978764` is not reported by the server at any point. This query method is the default method used by DZGUI. This ID actually points to a piece of UGC (user-generated content) on the Steam workshop: a screenshot of Euro Truck Simulator 2 (https://steamcommunity.com/sharedfiles/filedetails/?id=1396978764).

Why is this ID being returned? As a workaround for [DZG-001](https://aclist.github.io/dzgui/kb.html#DZG-001), DZGUI 5.4.1 introduced a fallback logic for querying servers. This is because due to the bug in DayZ's server<->client protocol, users switching between different wired/wireless networks may be unable to query servers directly. (This happens frequently with Steam Deck due to the fact that it's a wireless device used at home/work/etc.) 

This fallback query logic uses the Battlemetrics API as a last resort approach to finding the mod IDs. As it turns out, the Battlemetrics API returns incorrect/malformed mod IDs that have collisions with other content on the Steam workshop. (In this case, a screenshot of a game.)

In your case, DZGUI's default server query method was not being used. The fallback (Battlemetrics) method was being used, and it was inserting several bogus mod IDs.

Unfortunately, this is going to be a tricky one to resolve, since the fallback method was explicitly added in 5.4.1 because users on Steam Deck/Wi-Fi were having trouble connecting to servers at all, due to the aforementioned bug in the DayZ server<->client protocol. Thinking it would be better to allow them to connect than not at all, I added this secondary method, but it's not reliable. (And this has been a problem in the past with third-party APIs.) The mod IDs coming back from Battlemetrics are mostly accurate, but not sanitized, and contain collisions.

I could try to step through these IDs and verify that they are legitimate mods before requesting the download, but the fact of the matter is that the mod ID data is inherently unreliable unless we use DZGUI's default method. Battlemetrics reports several more irrelevant mods that are not actually needed for the MAG server (59 versus DZGUI's 55).

> Just a comment from me: If possible, you might look into changing DZGUI behaviour from verifying all mods when accessing a server to only verifying mods that are actually active and in use on that particular server.

This should not happen when using Manual mode. It is only a convenience/side effect of Auto mode, since DZGUI needs to keep track of mod signatures that are downloaded out-of-band (i.e., not manually Subscribed to).

> You are right. After unsubscribing from all mods on steampowered.com (browser, not the Steam client, just in case there is a sync issue) I was able to use DZGUI to verify mods and access the modded server.

I think what actually happened here is that your network conditions changed and DZGUI was able to use the default query method and get the right modlist. Due to the nature of the server query bug (a flaw in the DayZ client/server protocol itself), servers may periodically appear unreachable, even when they are unlocked and broadcasting.

I need to think about how to work around this. Obviously, since the bug has been present in some form in DayZ for over a decade, it's unlikely to be fixed any time soon. But users on Wi-Fi expect to be able to connect to servers (this problem seems to happen with MAG a lot, so maybe we can kick this issue up to the server administrators). However, we can't get invalid mod IDs when using a third-party server query method.

**Comment by aclist** [comment] 2024-10-05 18:33
I have issued a hotfix to both the Stable and Testing branches that should resolve this issue. It expands on the existing mod ID sanitization logic to ensure that not only are not "empty" mod IDs being treated as valid, but ones pointing to erroneous screenshots are excluded. This should ensure that even when using a fallback logic to query servers, the complete, full modlist is returned.

**Comment by KewDok** [comment] 2024-10-06 08:33
I am fairly confident you are right about the network issue being the cause. When I first attempted to launch the server in question using DZGUI I was on my company network. I know there are issues accessing DayZ servers from this particular network (it does not allow traffic on all ports), and I was pleasantly surprised that I could download mods. Sounds like the issue is with the data quality on Battlemetric's side, as you mention. In a scenario where it is not the first time I am launching a particular server you could prompt the user about the discrepancy between locally cached mods and Battlemetrics and give them the choice between attempting to log on anyway (and/or attempt to update) local mods only? I do not know how much of a niche my scenario is, so please prioritize only if this affects a lot of people.

Anyway, keep up the great work!

Brgds
KewDok

**Comment by aclist** [comment] 2024-10-07 00:32
Do not worry; I am confident that this issue should not recur for you or anyone else with this new fix.

As for "logging on anyway," it is a bit trickier than that, because we have to request to launch the game with a specific set of mods that the server tells us it has. That is in essence the reason for DZGUI's existence, as you cannot just "log on" to a server, you must specify which mods you are using.

Closing this as resolved. Feel free to reopen if you encounter problems.

**Closed by aclist** 2024-10-07 00:32 UTC
