### ISSUE TITLE
App is always opened in full screen mode

### ISSUE THREAD

**Issue by murkl** [aclist/dztui#157] opened 2024-10-11 11:57 UTC
Many thanks for the super helpful tool! However, it is a bit annoying that the application always opens in full screen (I'am using a WQHD Monitor). Would it be possible to change this somehow?

**Comment by aclist** [comment] 2024-10-11 21:20
Thanks for the message. I am also using  1440p. The default setting has changed a few times during DZGUI's development. Previously it opened in a small window. The issue is that the server browser table has so many fields in it, many of which contain important information, and you will have to scroll far to the right or maximize the application anyway in order to see them. Some users were not noticing these extra fields on the right of the table, so the default behavior was changed so that they can see these fields at the beginning.

Do you usually just scroll the table to the right, or do you not use those fields?

I suppose it could be made a toggleable option in the settings, the default (first time boot) being fullscreen.

**Comment by murkl** [comment] 2024-10-12 07:59
That makes sense to me. I mainly use dzgui to start my favorite servers, so I'm usually only interested in the number of players. I don't change servers too often :) An option to change the window behavior would be great. However, I can see all fields in the smaller window (but that is of course due to WQHD):

![Bildschirmfoto vom 2024-10-12 09-47-02](https://github.com/user-attachments/assets/c8839e7e-ea53-4bca-9dfe-d0e44f3caa5d)

**Comment by aclist** [comment] 2024-10-12 08:13
Your suggestion is reasonable; I will make this a changeable and sticky setting in the next release.

**Comment by murkl** [comment] 2024-10-12 08:16
Thank you very much, I really appreciate your work!!!

**Comment by aclist** [comment] 2024-11-02 14:27
This change has entered the `Testing` branch with version `5.5.0-beta.4` and will be merged into the mainline `Stable` branch soon. It is now possible to set your preference for "fullscreen at boot" as `true|false`. The default is `false` (OFF). 

Changing the option inside the application will not adjust the currently opened window; this only affects whether the application is maximized on launch.

**Comment by murkl** [comment] 2024-11-04 23:56
Thanks a lot! It works great. I've just tested it :)

**Comment by aclist** [comment] 2024-11-11 00:28
If you wish to revert back to the Stable branch, this feature is now live in version 5.5.0.

**Closed by aclist** 2024-11-11 00:28 UTC
