### ISSUE TITLE
New launch issue.

### ISSUE THREAD

**Issue by GKourp** [aclist/dztui#80] opened 2023-09-25 11:42 UTC
When launching from desktop mode or regular steam deck mode, I receive the warning of steam console taking focus and needing focus for mod receipt. I allow it to run after the warning and after a certain point and it runs for what seems to be hours. I've run it a few times at this point.

**Comment by aclist** [comment] 2023-09-25 21:23
This is a duplicate of #79. I already replied on there and asked some follow-up questions.

**Closed by aclist** 2023-09-25 21:23 UTC
