### ISSUE TITLE
Will not pull any mods for Sakhal map on update 1.26

### ISSUE THREAD

**Issue by rklxmok** [aclist/dztui#159] opened 2024-10-15 21:18 UTC
Returns "No mods listed", but the server has mods. 
![Screenshot_20241015_161713](https://github.com/user-attachments/assets/5a8091e5-6d31-4900-b515-d9f97ad5f155)
![Screenshot_20241015_161328](https://github.com/user-attachments/assets/b8a11c4e-41eb-481b-bf21-84ad3772e9c9)

Then it will not launch the game

**Comment by aclist** [comment] 2024-10-15 23:45
This sounds like a variant of [DZG-001](https://aclist.github.io/dzgui/kb.html#DZG-001). Make sure you have a Battlemetrics API key set (`Options > Change Battlemetrics API key`, https://aclist.github.io/dzgui/dzgui.html#_api_key_server_ids) so that DZGUI can use a fallback server lookup method in the event that your network prevents you from querying the server (usually the case with unorthodox Wi-Fi/mobile wireless networks, or switching between too many networks).

**Comment by rklxmok** [comment] 2024-10-15 23:56
Thanks! Adding the bm key did resolve it, I am curious why it only had an effect on sakhal servers though. I am also wondering if pihole may have something to do with it as well. My networking is pretty standard, all defaults on kde/arch.

**Comment by aclist** [comment] 2024-10-16 00:02
This issue affects a vanishingly small number of users and an even smaller number of servers, with seemingly no apparent pattern among them, so I am still trying to identify the root cause. It's pretty hard to reproduce in a controlled environment. It seems like servers periodically stop responding to queries--not sure if this is some anomaly, some form of anti-DDoS protection, improper implementation on the server-side, or something else. Only educated speculation at this point based on looking at Bohemia's bug tracker. If you find anything out, let me know.

**Comment by rklxmok** [comment] 2024-10-16 00:26
Actually no, this is even more strange. 
non sakhal
![image](https://github.com/user-attachments/assets/5edcc611-0b28-466d-a2a7-b0f84ca1393a)
every sakhal server now has wingdings lol
![image](https://github.com/user-attachments/assets/dc1eddc1-7125-4b1b-b77b-4c73064bb30c)

**Comment by leilawren** [comment] 2024-10-16 07:57
I am also having this issue. Things were working great before the update and Sakhal. 

So far I have renewed my Steam API key, as well as added a BM API key following the instructions in the DZGUI documentation. I also force updated all mods, to no avail. 

When I force updated mods, DZGUI did manage to talk to Steam to auto update, so that works.

**Comment by aclist** [comment] 2024-10-16 12:24
Thanks for the additional information. I wasn't aware of this new map or update until now. I had a look at the servers in question (with Sakhal map), and indeed there is something changed in the way the modlist is coming back from the server. (Generally unresponsive or claims it has no mods.) When this fails, we look up the modlist via Battlemetrics, but the corrupted mod names come from bad data quality on the Battlemetrics side.

Tomorrow I'll start investigating workarounds to this issue. My speculation is that servers running 1.26 and/or this map use a slightly different protocol for reporting the modlist.

**Comment by rklxmok** [comment] 2024-10-16 14:26
Thanks for all the hard work. Let me know if you need me to test the client. 

KB

**Comment by leilawren** [comment] 2024-10-16 19:23
Ur awesome <3

**Comment by mokee9** [comment] 2024-10-18 04:36
Also having this issue with a Sakhal map with light mods, Battlemetrics is also misreporting the server as having no mods.

**Comment by aclist** [comment] 2024-10-18 11:28
> If I right click to get the mod list, all of my saved servers are reporting their mod list properly (i.e. modded Chernarus servers running 1.26 update). I can also join these servers with zero issues.

- I confirm that servers running the 1.26 build but not Sakhal return the correct mod list.

- As an additional data point, official servers running the Sakhal map appear to be working correctly.

- Third-party, modded servers running Sakhal with any number of mods do not work correctly.

DZGUI utilizes a Python module to decode binary payloads returned by DayZ servers over the A2S protocol. These binary payloads deviate from Valve's specifications for A2S and introduce a custom logic used by Bohemia for packing data, in this case mod lists. Reverse engineering binary payloads is not my area of expertise; I have reported the issue to the author of the Python module, and hopefully the author has some insights to share.

I have tried some cursory changes to the decoding logic, but was unable to find the magic sequence to segment the data correctly thus far. 

This appears to be a wholesale change (as has happened before) to how mod lists are packed, and presumably affects all third-party launchers and query libraries (e.q. Battlemetrics, GameQ) until someone documents the inner workings of the new data structure. I have looked across various channels related to DayZ server administration and have not found much discussion about this issue yet, although a raft of other issues related to Sakhal were being reported.

I can't say for certain whether this change to mod lists is accidental or intentional on the developer's (Bohemia) side. For the time being, it doesn't seem to affect other game modes, although it could, eventually, supplant the standard method of broadcasting mod lists, in which case this would break all functionality.

DZGUI only uses Battlemetrics as a method of last resort when querying servers directly fails. In this case, the main query method is failing, as is the backup method (Battlemetrics), so neither of the mod lists are reliable. This might lead DZGUI to think there are no mods, or to find a malformed list of mods and try, but fail, to fetch them. This behavior is indicative of only one thing, which is that the mod list data could not be decoded. This might manifest itself in a variety of strange bugs, but the cause is the same.

In the interim, I may try to clarify the wording in the error message: at the very least, DZGUI should not report the server as having "no mods", but should say that the modlist could not be decoded correctly. (Essentially, failure to decode the modlist returns an "empty" result, which was triggering the "no mods" message.) While this won't fix the root cause, it should at least remove ambiguity for now.

**Comment by leilawren** [comment] 2024-10-18 20:01
Thanks for the effort. Hopefully the DayZ devs are able to address this at some point.

**Comment by rklxmok** [comment] 2024-10-18 20:46
@aclist this update has been terrible on the Linux side. The launch options stopped working correctly on my Linux dz servers, I am forcing core and thread count to correct it now when I didn't have to before, this issue is across all mission types. Many mods wont even work at all anymore, but only for the sakhal mission. Rcon is completely broke as well globally on Linux servers, at least with the distros I have spooled up anyways, ub22 and ub24. So I can't even register them on battlemetrics. Still wont use windows though. Keep up the good work and thanks for looking deeper into this.

**Comment by mokee9** [comment] 2024-10-18 23:24
@aclist Instead of relying on the server to report a list of mods could it be possible to have backup feature to force the client to load the mods you need (like a checklist of all installed workshop mods) for the server and then connect via IP/ID etc? 
It would be up to the user to know what mods are needed though.

**Comment by aclist** [comment] 2024-10-19 02:29
> @aclist this update has been terrible on the Linux side. The launch options stopped working correctly on my Linux dz servers, I am forcing core and thread count to correct it now when I didn't have to before, this issue is across all mission types. Many mods wont even work at all anymore, but only for the sakhal mission. Rcon is completely broke as well globally on Linux servers, at least with the distros I have spooled up anyways, ub22 and ub24. So I can't even register them on battlemetrics. Still wont use windows though. Keep up the good work and thanks for looking deeper into this.

I was looking through the "known issues" section of the patch notes, and indeed it seems that a large amount of stuff is broken, and that is just for the known bugs. Hopefully some of this resolves itself over time. On the mod side, I would venture to guess mod authors would need to make adjustments for compatibility. If RCON is broken as well, maybe the A2S issue is unintentional. The A2S responses are already highly elaborated, so I'm not sure why the data structure would need to change at this point unless even more data eeds to be sent for Sakhal servers in particular, although at first glance the data structure didn't really look too different to me from normal maps. (A2S_RULES is supposed to return plaintext information on game rules, and has a length limit. Bohemia decided to cram this with binary payloads to overcome the length limit and this method is underspecified, as far as third-party developers are concerned.)

> @aclist Instead of relying on the server to report a list of mods could it be possible to have backup feature to force the client to load the mods you need (like a checklist of all installed workshop mods) for the server and then connect via IP/ID etc? It would be up to the user to know what mods are needed though.

This has been brought up a few times before, but I couldn't reconcile the viability. Servers constantly change the mods they need, so there is no "single source of truth" on the modlist other than what the server reports. Could you cache the last known modlist? Yes, but it is liable to change, so then we are carrying around stale modlist information. On the other hand...connecting to a server requires you to specify all the mods you need a priori, so your idea to beef up the launch parameters with essentially all of the mods the user has installed (even if we don't need them) might actually work, but I'd need to test it. I don't know if the server would reject this, or what the performance implications (if any) might be.

Secondly, this puts a lot of additional work on the user. I know it's a method of last resort, but users expect a turnkey approach that "just works", so having to go and find all of the mods (from where? I guess the official launcher, since no other modlist data is trustworthy for Sakhal maps right now) feels like a big ask. You'd have to first find them, then manually subscribe to them.

There's also a third problem: due to a limitation in the Steam client, you can't pass unreasonably large launch parameters. (There's a length cutoff.) If we crammed all of the user's installed mods (let's say 150) into the launch options, it's liable to be so long that even Steam can't handle it.

Maybe there is something else that blends all of the above: show the user a list of their installed mods and let them multi-select (via checkbox) the ones they need, then let DZGUI convert these into the right launch parameters and hand it off to Steam. This still seems finicky (also, what if the user has 100s of mods to choose from? Probably need a bulk Select All/Select None radio option as well), but it might be doable. It also seems kind of overengineered for something that should just work (decoding modlist from the server). This would be a non-trivial amount of work to implement, although we could recycle the "List installed mods" menu. Unfortunately, it would only help the most technically-minded/DIY users.

**Comment by rklxmok** [comment] 2024-10-25 13:50
EXCELLENT

**Comment by aclist** [comment] 2024-10-26 15:05
About the fix
---
Thank you for waiting. I have an exciting update for you today.

After considering various approaches and not hearing from the original author of the Python module, I decided to study the data structure more closely, and hire an additional engineer on a bounty basis to lend a hand.

Considering the real possibility that there may be other DLC in DayZ's future, the fix needed to be robust enough to support future DLCs down the line, rather than a band-aid fix for Frostline in particular. Furthermore, the fix should integrate seamlessly with the existing approach to fetching modlists, rather than being a one-off solution.

As of yesterday, I was fairly confident that with our new solution, modlists were being parsed correctly. Everything was looking correct on the data front, but I had not been able to test this functionality end-to-end (connect to actual Frostline servers in-game), since the DLC is required. Everything looked alright when trying to connect, but since I was getting kicked out, I couldn't be sure.

But then...thanks to a generous donation from a sponsor that offset the cost of the Frostline DLC, I was finally able to verify this new logic against multiple live Frostline servers and confirm that modlists are being parsed correctly, mods are being fetched, and I can load into these servers (modded or otherwise) without problems. In addition, features such as showing server-side mods also behave as expected.

Intermission: a humble request from your developer
---

DZGUI is free software. It has been continuously developed and maintained by one person for three years. I try to respond with alacrity (24-48 hour response time) to emerging issues and troubleshoot non-bugs (user error or general questions) constantly across a variety of channels.

Over the three-year lifecycle of this project, there has been a handful of donations from about 5-6 users, which totals maybe .01% of DZGUI's userbase. I've never asked for donations, and the sponsorship link is intentionally buried: it's there only for those who are really enthusiastic about funding the development of free software and are willing to find the page.

Deepest thanks to those users, and to those who have volunteered their time with feedback and testing, like those of you reading this bug ticket right now!

However, as a result of issuing this fix for the Frostline DLC, the DZGUI community chest (tip jar) **is now empty**. A summary of expenses to date follows:

- Steam Deck test bench
- Frostline DLC
- Wages for additional contractor (one-time)

In terms of the one-off wages for the extra engineer, what I could not cover with the community chest I have paid out of pocket, (which is the majority). Going forward, it's reasonable to assume that in the future, there may be some project incidentals that call for extra expenses. For example:

- Steam Deck OLED test bench (not yet procured)
*The OLED version has a different architecture and base system files that affect how the UI is drawn. This currently affects a subset of DZGUI users and I cannot test it by hand right now.
- Future DLCs
- Some particularly tricky issue that calls for hiring a contractor

I do not want to hold the code hostage, but I want to suggest a compromise:

If you would like to see this hotfix released as soon as possible, and are enthusiastic about supporting DZGUI, please [consider sponsoring with a one-time donation](https://github.com/sponsors/aclist?frequency=one-time&sponsor=aclist). If just five users leave a one-time $20 sponsorship (or ten users with a $10 sponsorship, or 20 users with a $5 sponsorship), I think this would replenish the community chest enough that I can continue to offset other incidentals out of pocket. If your friends are using DZGUI, encourage them to consider doing the same.

If this milestone is not reached, I will continue stress testing the fix and bundle it into the next release of DZGUI, which will follow the major version cadence and come a bit more slowly, as other features and fixes need to be integration tested.

Please give me your thoughts and tell me if this is a reasonable approach. As in the example with the Frostline DLC, your donations actually help accelerate development. There's no good substitute for testing things using the real product/device.

Closing thoughts and discussion
---
Consider the issue in this ticket resolved. I am confident that this forthcoming fix should address all of the issues and allow you to play on Frostline servers. The fix is staged to go into the Testing branch so that we can see how it behaves in the wild.

Note that if you are affected by [DZG-001](https://aclist.github.io/dzgui/kb.html#DZG-001) (chiefly affects users jumping across LAN devices) and DZGUI switches to the Battlemetrics API as a fallback, this may not work, as BM is not parsing server responses correctly.

For the vast majority of users, and Steam Deck users, this Frostline DLC bug is fixed.

Ideally, I'd like to move away from using BM as a fallback; we've tried it once before, and the data quality was not reliable. But it's there as a method of last resort instead of giving users no other option. Until the underlying bug in the DayZ server protocol that causes the timeouts in DZG-001 to occur is resolved (it's out of my hands), the only alternative that comes to mind is making a standalone DZGUI API endpoint (e.g. dzgui dot com), and serving proper modlist data via that.

The main problems with this approach should be obvious:

- Entails running costs
- Requires additional network administration and abuse prevention
- No guarantee that this endpoint could be available in perpetuity

I believe the best approach for the end-user on a local PC continues to be trying to talk to servers directly where possible, rather than building third-party APIs around DayZ.

**Comment by rklxmok** [comment] 2024-10-26 15:50
I will for sure place a donation and very much appreciate the effort put into this. It is quite funny that you and your team corrected it before bm was able to, I had just pulled up a server on bm to see if they had fixed it right before your reply, they are still retrieving wingdings. Thanks @aclist

**Comment by aclist** [comment] 2024-10-27 17:03
@rklxmok Thank you.

**Comment by aclist** [comment] 2024-10-30 14:12
DZGUI `5.5.0-beta.1` is available on the `Testing` branch (`Options > Toggle release branch`).

Please test and report back on whether you are able to retrieve server-side modlists and connect to Sakhal servers.

This hotfix also adds a change to the maps dropdown combobox: this widget now includes a text field with search autocompletion. You can start typing a string and the completer will show matching maps. You can arrow through these and hit Enter to filter for that map. This should obviate the need to scroll through the long map list when you have a specific map in mind.

E.g., start typing `sa` to see possible matches. This should return:

- sahrani
- sakhal
- salov

Obviously, a more restrictive search like `sak` will only return `sakhal`.

Remember, you can invoke the keybinding `Ctrl-m` to enter the maps field, and `ESC` to restore focus to the main table. Unlike the keyword field (free search), in the maps field, it is not possible to search by nonexistent map names.

**Comment by rklxmok** [comment] 2024-10-31 00:52
@aclist 
Confirmed, I have tested 5 servers, none have returned wingdings
![image](https://github.com/user-attachments/assets/d7129410-899b-49b2-92b1-a9dc5b725b70)

**Comment by rklxmok** [comment] 2024-10-31 00:55
However, I cant type in the filter box at all, but can type in the map list box and do see the map drop down list

**Comment by aclist** [comment] 2024-10-31 07:42
> However, I cant type in the filter box at all, but can type in the map list box and do see the map drop down list

This has been fixed.

Separately, there is a small visual anomaly that is causing the map dropdown list to be duplicated into two columns, but functionality is otherwise not affected.

**Comment by aclist** [comment] 2024-10-31 07:55
> Separately, there is a small visual anomaly that is causing the map dropdown list to be duplicated into two columns, but functionality is otherwise not affected.

This is also fixed.

**Comment by rklxmok** [comment] 2024-10-31 13:59
You are a super hero. Thanks - Confirmed. I will keep testing and see if I can find anything else.

**Comment by aclist** [comment] 2024-11-11 00:28
If you wish to revert back to the Stable branch, this feature is now live in version 5.5.0.

**Closed by aclist** 2024-11-11 00:28 UTC
