### ISSUE TITLE
Not launching through steam shortcut

### ISSUE THREAD

**Issue by mdotpreis** [aclist/dztui#56] opened 2023-01-31 06:23 UTC
I'm using a steam deck running steamOS and the application launches in desktop mode using the desktop icon.  However when adding the desktop shortcut to steam it doesn't launch in desktop mode or game mode, it launches initial setup but closes immediately.

**Comment by aclist** [comment] 2023-01-31 14:46
I'll look into this on my test bench. IIRC, you should be adding the file below as specified in the documentation:

> Navigate to $HOME/.local/share/applications/ and select dzgui.desktop

Were you trying to add the shortcut file that was on the desktop? I think that could cause problems.

**Comment by aclist** [comment] 2023-02-01 15:46
I noticed that you closed this. Does this mean you were able to get it working?

**Comment by mdotpreis** [comment] 2023-02-01 16:38
> I noticed that you closed this. Does this mean you were able to get it working?

No lol I've just never used GitHub.  I used that directory but same results

**Comment by aclist** [comment] 2023-02-01 18:51
Alright, will investigate further then. Thank you.

**Comment by aclist** [comment] 2023-02-01 23:19
Is this on the stable or testing branch? I tested it with an older version and the newest version (3.2.2) and it works correctly via gaming mode as well. Can you go to the game's properties (gear icon) and see what it lists for `TARGET` and `START IN`?

Did you add this shortcut via desktop mode or via gaming mode? (Asking because I don't know if they've added a new way of adding non-Steam games via gaming mode and you maybe used that. It's recommended to add the shortcut via desktop mode)

Do you have anything special in the `Launch Options` field?

Did you set a specific Steam Play compatibility tool?

**Comment by aclist** [comment] 2023-02-02 17:49
OK, I'll have to add some additional logging output to the application so we can see where it is choking when launched in game mode.

**Comment by aclist** [comment] 2023-02-03 06:50
Sorry you are experiencing this. I have a couple unfounded theories as to why it might be happening, but this is the only report I've seen of it so far and I wasn't able to immediately reproduce the behavior here.

I pushed a small update to the Testing branch. You can toggle to the Testing branch via the Advanced Options. After it updates, run the application as before using the Steam shortcut and see how far it gets. After it fails, find the file `/tmp/dzgui.log` and paste its contents here. We'll start with fairly simple logging to see where it might be failing, then make it more verbose as necessary.

I also updated Steam Deck to the latest version and still was not able to reproduce this issue. Can you confirm the following:

Via Gaming Mode > System > Beta Participation

- OS Update Channel = ?
- Steam Client Update Channel = ?

**Comment by mdotpreis** [comment] 2023-02-03 15:55
[dzgui.log](https://github.com/aclist/dztui/files/10580453/dzgui.log)

OS Update channel and client are both running stable

**Comment by aclist** [comment] 2023-02-03 20:52
OK, it looks like all initial setup completes and it does proceed to the main menu creation. (My initial hypothesis was that it was failing partway through the initial setup dialog). I've added some more error output that should hopefully capture what happened when the main menu window crashed. Please update and try again, then post log output here.

**Comment by mdotpreis** [comment] 2023-02-03 21:28
[dzgui.log](https://github.com/aclist/dztui/files/10582879/dzgui.log)

Updated and submited the log.  I now get a dialog box that won't close and reopens when pressing `Ok` and says 
>No item was selected.

**Comment by aclist** [comment] 2023-02-04 04:06
OK, based on that, I'm fairly certain one of the parameters (probably related to setting the right resolution for SD) when we construct the main menu is getting dropped or not concatenated correctly, but only when executed through Steam's subshell. I think we are closing in on a fix here. Looks like zenity is trying to parse an argument that is supposed to be a valid option but is rejecting it as invalid.

I've changed a few things around and added some more logging, so can you please try again? Thanks for your patience.

**Comment by aclist** [comment] 2023-02-04 04:16
Make sure you are using version 3.3.0-rc.12 when testing

**Comment by aclist** [comment] 2023-05-14 07:31
@mdotpreis 

A much belated response, but the root cause of this problem was finally tracked down thanks to a detailed report from a user. This is an obscure case involving certain Steam Deck configurations and the initial setup menu getting destroyed when it spawned due to a regression in the GUI library. This issue has been fixed in the latest stable version and setup and launch should run end-to-end on Steam Deck. If you haven't tried this in awhile, I suggest redownloading and trying it.

Apologies that this took so long to track down, but due to the infrequency of the bug, there was no conclusive information to go on until a user shared extensive videos and logs taken from a Steam Deck.

**Closed** 2023-05-15 00:54 UTC
