### ISSUE TITLE
[BUG] Fedora 38 version of zenity causes segfault

### ISSUE THREAD

**Issue by Arbitrate3280** [aclist/dztui#74] opened 2023-06-18 03:59 UTC
I wish I could give more details, but there's no terminal output. I open it, it shows me the "Initial run" screen and then crashes.

**Comment by aclist** [comment] 2023-06-18 06:20
I'm in the proces of rewriting the logging framework because the progress popups provided by zenity are built in such a way that they swallow stdin in certain cases. I also want to write a more robust text log to a file so that users can paste it back for troubleshooting purposes.

There is a barebones log that should appear in `/tmp/dzdebug.log` if this is the first time the program is run. There is tech-debt here, as the logging is lacking. I'll try to make time to build out this functionality this weekend.

As for the issue, for starters, is this the first-time setup, or just a normal invocation of the program?

Did you invoke it manually through the terminal, through a shortcut, or did you add it to Steam directly?

**Comment by aclist** [comment] 2023-06-18 06:24
Sorry, my last question was rather ignorant (just woke up). Based on how you worded your comment, I'm going to assume you invoked it through a terminal.  In that case, please start by checking for the presence of the log file.

When I get back to the desk, I'll push an update that includes more verbose logging so that you can tell me at what point it's crashing, so that we aren't playing blind here.

**Comment by aclist** [comment] 2023-06-18 12:56
Hello, I have pushed a new version (`3.3.3`). Can you please update through the app or redownload if you haven't completed first-time setup yet?

After launch, DZGUI will generate a file `DZGUI_DEBUG.log` in the directory it was run from. It should give us a view into how far the initial setup is getting before crashing. Can you paste it here?

Thanks.

**Comment by Vitorvlv** [comment] 2023-06-18 19:24
>  Based on how you worded your comment, I'm going to assume you invoked it through a terminal. 

That's right.

> Can you please update through the app or redownload if you haven't completed first-time setup yet?

Alright, now I have a log, but unfortunately doesn't seem to have much information in it.
[DZGUI_DEBUG.log](https://github.com/aclist/dztui/files/11782420/DZGUI_DEBUG.log)

**Comment by aclist** [comment] 2023-06-18 19:41
That's fine, this is approximately where I expected it to fail. 

Were you prompted to enter your sudo password at all after this step in order to check the system vm map count?

Can you supply the output of the below command?

`sudo sysctl -q vm.max_map_count`

**Comment by Vitorvlv** [comment] 2023-06-18 19:42
> Were you prompted to enter your sudo password at all after this step in order to check the system vm map count?

No

> Can you supply the output of the below command?

vm.max_map_count = 65530

**Comment by aclist** [comment] 2023-06-18 20:41
OK, I am thinking. I had to step off the desk momentarily.

I think the error is definitively happening somewhere in the map count function and not going to the next step, so I've added more granular logging so that we can hopefully see where, exactly, that occurs. I've bumped the version to `3.3.4` and you should update again and paste your log.

Depending on the results, we may have to keep adding more granular logs until identifying the root cause. Thank you for your patience.

**Comment by Vitorvlv** [comment] 2023-06-18 20:44
```
[2023-06-18 17:43:41] [INFO] run_depcheck
[2023-06-18 17:43:41] [INFO] watcher_deps
[2023-06-18 17:43:41] [INFO] check_architecture
[2023-06-18 17:43:41] [INFO] Setting architecture to 'desktop'
[2023-06-18 17:43:41] [INFO] check_version
[2023-06-18 17:43:41] [INFO] check_branch
[2023-06-18 17:43:41] [INFO] Branch is stable
[2023-06-18 17:43:42] [INFO] Upstream version is 3.3.4
[2023-06-18 17:43:42] [INFO] Local version is same as upstream
[2023-06-18 17:43:42] [INFO] check_unmerged
[2023-06-18 17:43:42] [INFO] check_map_count
[2023-06-18 17:43:42] [INFO] Checking system map count
[2023-06-18 17:43:42] [INFO] Return code is 1
[2023-06-18 17:43:42] [INFO] Zenity dialog failed or user exit

```

**Comment by aclist** [comment] 2023-06-18 20:56
Follow-up questions:

What is the output of:

`whereis zenity`

Does the below command create a popup dialog?

`zenity --question --width 500 --title="DZGUI" --cancel-label="Cancel" --ok-label="OK" --text "sudo password required to check system vm map count." 2>/dev/null`

**Comment by Vitorvlv** [comment] 2023-06-18 21:00
```
whereis zenity
zenity: /usr/bin/zenity /usr/share/man/man1/zenity.1.gz

```

> Does the below command create a popup dialog?

It does

**Comment by aclist** [comment] 2023-06-18 21:07
What is the output of `zenity --version`?

If it's > 3.44.1 (I'm expecting it to be about 3.90+ on Fedora38), is it possible to try downgrading the zenity package?

**Comment by Vitorvlv** [comment] 2023-06-18 21:10
3.92.0

With dnf downrgade I can only downgrade to 3.91, I did that and the same error happens.

If you want I can try to figure it out how I can get an older version.

**Comment by aclist** [comment] 2023-06-18 21:15
I'm seeing some anecdotal reports about bugs with GTK and the newer version of zenity in Fedora 38 (i.e. not functioning the way it did in Fedora 37), but I think I'd rather just find a workaround in the code before taking drastic measures. I don't want to whitelist this step of the setup either, because other users need it. 

I may have found a fix, it's probably just parsing the arguments strictly and needs the width value to be directly adjacent instead of word split. Updated to `3.3.5`, please try again.

**Comment by Vitorvlv** [comment] 2023-06-18 21:38
Sorry, I might be missing something, it's still at 3.3.4 for me.

**Comment by aclist** [comment] 2023-06-18 21:47
Right, should be live now.

**Comment by Vitorvlv** [comment] 2023-06-18 21:54
Still at 3.3.4 for me, I'm getting the latest dzgui by doing git clone this repository, it's there some other way I should be getting it?

**Comment by aclist** [comment] 2023-06-18 21:57
Once you have the script configured, there is an auto-update feature built in that will check for the latest version on launch and prompt you to update your local version if there is a mismatch. There's no need to keep cloning the repo.

But it looks like my last commits weren't sticking, so I've pushed those again on all branches to update the version.

**Comment by Vitorvlv** [comment] 2023-06-18 22:04
Alright, the log is the same, but now I have this output in the terminal:

> GDBus.Error:org.freedesktop.DBus.Error.NoReply: Remote peer disconnected

**Comment by aclist** [comment] 2023-06-18 22:29
This is fine, it is just GTK warning logs. 

Well, I know exactly what line it is failing on, but can't understand why right now. I can't reproduce it. It may be the newer version of zenity, may not be. I don't want to keep you blocked from using the application any longer, so I'll make a note to investigate this in a Fedora VM and see if what the extent of the impact is.

To workaround this issue and prevent the map count check from triggering again, do the following:

`sudo echo "vm.max_map_count=1048576" > /etc/sysctl.d/dayz.conf`

DZGUI will skip that step in the future provided this file exists. Hopefully no other dialogs fail after you get past this step.

**Comment by Vitorvlv** [comment] 2023-06-18 22:33
Alright, this is the log now

```
[2023-06-18 19:32:35] [INFO] run_depcheck
[2023-06-18 19:32:35] [INFO] watcher_deps
[2023-06-18 19:32:35] [INFO] check_architecture
[2023-06-18 19:32:35] [INFO] Setting architecture to 'desktop'
[2023-06-18 19:32:35] [INFO] check_version
[2023-06-18 19:32:35] [INFO] check_branch
[2023-06-18 19:32:35] [INFO] Branch is stable
[2023-06-18 19:32:35] [INFO] Upstream version is 3.3.5
[2023-06-18 19:32:35] [INFO] Local version is same as upstream
[2023-06-18 19:32:35] [INFO] check_unmerged
[2023-06-18 19:32:35] [INFO] check_map_count
[2023-06-18 19:32:35] [INFO] Checking system map count
[2023-06-18 19:32:35] [INFO] fetch_helpers
[2023-06-18 19:32:35] [INFO] config
[2023-06-18 19:32:35] [WARN] Config file missing
[2023-06-18 19:32:35] [INFO] steamsafe_zenity is /usr/bin/zenity
[2023-06-18 19:32:35] [INFO] Return code 1
```

**Comment by aclist** [comment] 2023-06-18 23:00
OK, it seems like every time it tries to create a simple dialog prompting the user for something, it is failing. This is  a big blocker because we depend on these dialogs to run the user through initial setup. This seems localized to Fedora 38, as I haven't been able to reproduce it and have never seen this report before from other distros.

I'll try to set aside some time to mock this in a VM. I'm not sure what would be the most expedient approach here for you in the interim. If you have a Fedora 37 computer lying around, you could use it as a control. I'm not sure how far back you are going to be able to manually rollback without encountering dependency conflicts, since zenity is closely bound to GTK3.

https://unix.stackexchange.com/questions/266888/can-i-force-dnf-to-install-an-old-version-of-a-package

What I don't understand is why the same command worked when you invoked it from the terminal. I need some time to investigate this.

How urgent is this for you?

**Comment by Vitorvlv** [comment] 2023-06-18 23:22
> How urgent is this for you?

It's not, this would be the first time I would use this tool, so don't worry about it!! 

Take your time.

**Comment by aclist** [comment] 2023-06-18 23:50
OK, I am really sorry that the first-time experience did not go well. I will update this ticket as soon as I figure out what is going on. Thank you.

**Comment by aclist** [comment] 2023-06-18 23:57
One more question I had was if you are using a bash shell, or some other shell like zsh/fish/etc.

**Comment by Vitorvlv** [comment] 2023-06-18 23:58
Using a bash shell

**Comment by aclist** [comment] 2023-07-24 22:24
Thanks for checking in. I've been investigating it for the past month, but have yet to find anything conclusive. I have a possible lead, so will be running some tests again today.

May I ask what gave you the idea to invoke sudo here? A few users have reported doing that, so I'm trying to understand if there is something in the initial setup wording/presentation that is suggesting you should do that, or whether users are trying it as a last resort. You should not invoke DZGUI or Steam as root, it is not going to work and is liable to cause problem.

**Comment by loissascha** [comment] 2023-07-24 23:25
I tried it a while ago and I think back then I was checking the dzgui.sh file if I could find the line where it fails and I think it looked like the line where it was asking for the sudo password for the map size check or something. So I thought probably the password dialog was broken and I'd just give it sudo permissions to skip that. I didn't find any information about this problem when I was searching for it the first time so it kinda was the last thing I was able to do. 

Today I did some extended research about this problem because I wanted to play with some friends and that's how I came across this ticket. Thought maybe it'd help to know that the dialogs itself seem to be working (atleast as root), because you said it's maybe an issue with zenity itself. I guess you probably figured that out yourself already.
Maybe I was kinda hoping you had some sort of manual workaround that temporarily fixes it or whatever ;D

**Comment by loissascha** [comment] 2023-07-25 00:02
Okay I think I figured something out.

I just duplicated this line:
`$steamsafe_zenity --width=500 --info --text="Config file not found. Click OK to proceed to first-time setup." 2>/dev/null`
and for whatever reason, it worked. If I remove one line it doesnt work. The dialog does not show up 2 times or whatever.

And after finishing the first time setup and successfully launching the game from the launcher I closed it and it didnt work again. I guess because it didn't hit this extra line I added, so I checked the log file again and added this line:
`$steamsafe_zenity --width=500 --info --text="Initial Zenity" 2>/dev/null`
at the beginning of the set_header function, because that's where it stopped working after the initial setup. Sometimes it does show the "Initial Zenity" info dialog, but most of the time it doesn't. It kinda looks like the first time trying to create any zenity window it just fails or something and if you just do it again it works from there on. 

I know that's a janky fix, but maybe you can utilize this information

**Comment by aclist** [comment] 2023-07-25 00:31
Actually, I have identified the root cause, it is not related to the above. The much newer version of zenity available in fedora does not seem to respect its own settings or the ones used in older versions, so I think this problem might eventually affect other distributions once they upgrade to the newer package. I have a fix worked up, please stand by. I need to think about how to make this work well on other systems without dropping existing functionality.

**Comment by aclist** [comment] 2023-07-25 01:03
Alright, so the main issue is that the initial setup routine spawns a progress dialog ("Initial setup...") while background routines and checks are performed, but some of these routines themselves spawn zenity dialogs, such as the vm map count (sudo prompt) and config setup dialogs.

The newer version of zenity does not seem to respond well to nesting itself in this way, and this was blocking the initial entry point of the script, causing it to crash when the second dialog was spawned after the progress dialog. This categorically works on older versions and is by design, but the newer version always segfaults when invoked this way. This may also be related to upstream GNOME, as it spits out the error `GDBus.Error:org.freedesktop.DBus.Error.NoReply: Remote peer disconnected` when crashing.

For now, I've changed it to stop spawning the progress dialog if the zenity version is greater than or equal to `3.91.0`. I haven't found a good way to display this initial setup dialog on the new zenity version, but it doesn't affect core functionality. It just gives the user some "presence notification" so that they know DZGUI is checking a few things at the beginning, but is not essential.

This should clear the blockage and allow first-time setup to run and the rest of the app to work. However, there *may* be other areas where nested dialogs are used (I don't think so, but it's possible), so if any other part of the DZGUI menu triggers a similar crash, such as when downloading mods and getting progress notifications, please report it here.

@Vitorvlv this should resolve the originally reported issue.

Meanwhile, I will try to see if we can restore the initial progress dialog in a way that supports the newer zenity, or use an alternate method.

**Comment by loissascha** [comment] 2023-07-25 12:40
Thanks a lot, this fixed it for me.

**Comment by aclist** [comment] 2023-07-25 21:19
Thanks for confirming. Once the underlying bug in zenity is resolved, we should be able to restore the initial progress dialog on Fedora.

**Comment by Vitorvlv** [comment] 2023-07-25 22:02
The setup is now working as expected, but the server browser is not working.

Don't know if this is related to this issue or if it should be it's own thing.

It shows the server list for a second and then returns to the main screen.

Terminal output:
```
# Initial setup
[DZGUI] Setting architecture to 'desktop'
[DZGUI] Upstream (3.3.7) != local (3.3.9)
[DZGUI] Checking system map count
# Checking news
100
./dzgui.sh: linha 1388: printf: 6545.1: número inválido
./dzgui.sh: linha 1388: printf: 8664.1: número inválido
./dzgui.sh: linha 1388: printf: 9429.5: número inválido
./dzgui.sh: linha 1388: printf: 10712.2: número inválido
./dzgui.sh: linha 1388: printf: 7515.8: número inválido
```
[DZGUI_DEBUG.log](https://github.com/aclist/dztui/files/12165954/DZGUI_DEBUG.log)


Short video showing what's happening

https://github.com/aclist/dztui/assets/26132870/c1e83264-ec22-4913-aaff-41f6ce67b424

**Comment by Vitorvlv** [comment] 2023-07-25 22:19
I added a server ID manually just to give it a try. Another interesting issue is that it started spawning windows when I tried to join a server
[Screencast_20230725_191619.webm](https://github.com/aclist/dztui/assets/26132870/cf63d674-3598-4188-b2cc-1f2e9e32c635)

Spamming the OK button made it go away.

**Comment by aclist** [comment] 2023-07-25 22:46
About the first issue, it seems to be locale related since you use comma for decimals. What's the output of this command?

`locale`

And this command?

`LC_NUMERIC=C printf "%05.0f\n" 6545.1`

As for the second, wasn't able to reproduce the recursive windows on my local setup, will try in the Fedora VM again.

**Comment by Vitorvlv** [comment] 2023-07-25 22:54
locale output:
```
LANG=pt_BR.utf8
LC_CTYPE="pt_BR.utf8"
LC_NUMERIC=pt_BR.utf8
LC_TIME=pt_BR.utf8
LC_COLLATE="pt_BR.utf8"
LC_MONETARY=pt_BR.utf8
LC_MESSAGES="pt_BR.utf8"
LC_PAPER=pt_BR.utf8
LC_NAME=pt_BR.utf8
LC_ADDRESS=pt_BR.utf8
LC_TELEPHONE=pt_BR.utf8
LC_MEASUREMENT=pt_BR.utf8
LC_IDENTIFICATION=pt_BR.utf8
LC_ALL=
```

LC_NUMERIC=C printf "%05.0f\n" 6545.1 output:
06545

I tried another server and it didn't happen, so might be something particular about this one server, I can reproduce the issue every time with it.

Here's the server ID in case you want to test it: 18767953

**Comment by aclist** [comment] 2023-07-26 00:32
Alright, I released a hotfix for the server browser, let's see if it works. I'll look into the second issue.

**Comment by loissascha** [comment] 2023-07-26 12:24
Oh yeah, I haven't tried the server browser yesterday but I'm having the same issue with it. With the last version I also had this invalid number thing, and with the new version you released it still just closes itself after like a second but without showing the error message.

**Comment by aclist** [comment] 2023-07-26 22:36
Alright, I believe it is related to zenity again, as the server browser window is a secondary window, which seems to conflict with the first window drawn by zenity. This is definitively a zenity bug, so I think we should wait for the maintainers to fix it, otherwise we will be rewriting most of the core of DZGUI for a fleeting issue.

**Comment by aclist** [comment] 2023-08-06 06:44
This issue has been reported upstream to the GNOME project and I am awaiting further feedback on a bug fix.

**Comment by aclist** [comment] 2023-08-09 10:13
@Vitorvlv  @loissascha 

Hello, thank you for waiting. We have some progress on the zenity front from one of the Fedora package maintainers here: https://gitlab.gnome.org/GNOME/zenity/-/issues/61#note_1810359

In short, the bleeding-edge version of zenity in the development branch of Fedora fixes it, but this has not been integrated into Fedora 38. However, you can build the more recent version of zenity to pull in those patches.

Can you try compiling the upstream version of zenity from source and seeing if it resolves it?

**Comment by aclist** [comment] 2023-09-13 08:23
This bug has been resolved in the latest version of zenity. If you have not updated your Fedora system yet, you can upgrade to the latest version of zenity (`zenity-3.99.1-1.fc38`) via the following command:

`sudo dnf upgrade --refresh --advisory=FEDORA-2023-424fb4c3dd`

**Comment by aclist** [comment] 2023-11-02 14:22
In light of a new regression reported [here](https://gitlab.gnome.org/GNOME/zenity/-/issues/71) that affects the server browser, I am reopening this ticket until it is resolved.

**Closed** 2023-12-03 10:42 UTC
Labels: bug
