### ISSUE TITLE
Steam Deck Log (Server Issues)

### ISSUE THREAD

**Issue by Jott007** [aclist/dztui#106] opened 2024-03-29 01:24 UTC
2024-03-28 21:15:26,867␞INFO␞/home/deck/Games/dzgui.sh::setup_state_files()::94␞Initializing DZGUI version 5.2.0
2024-03-28 21:15:26,871␞INFO␞/home/deck/Games/dzgui.sh::setup_state_files()::106␞Wiped cache files
2024-03-28 21:15:26,872␞INFO␞/home/deck/Games/dzgui.sh::depcheck()::225␞Initial dependencies satisfied
2024-03-28 21:15:26,884␞INFO␞/home/deck/Games/dzgui.sh::check_pyver()::234␞Found Python version: 3.11.3
2024-03-28 21:15:26,923␞INFO␞/home/deck/Games/dzgui.sh::test_gobject()::136␞Found PyGObject in Python env
2024-03-28 21:15:26,925␞INFO␞/home/deck/Games/dzgui.sh::watcher_deps()::241␞Found DZG Watcher dependencies
2024-03-28 21:15:26,929␞INFO␞/home/deck/Games/dzgui.sh::check_architecture()::392␞Setting architecture to 'desktop'
2024-03-28 21:15:27,216␞INFO␞/home/deck/Games/dzgui.sh::fetch_a2s()::510␞A2S helper is current
2024-03-28 21:15:27,254␞INFO␞/home/deck/Games/dzgui.sh::fetch_dzq()::526␞DZQ is current
2024-03-28 21:15:27,796␞INFO␞/home/deck/Games/dzgui.sh::fetch_helpers_by_sum()::568␞vdf2json.py is current
2024-03-28 21:15:27,802␞WARN␞/home/deck/Games/dzgui.sh::fetch_helpers_by_sum()::570␞File '/home/deck/.local/share/dzgui/helpers/ui.py' checksum != '05a84408e1d375a38a899b715c38da6e'
2024-03-28 21:15:28,106␞INFO␞/home/deck/Games/dzgui.sh::fetch_helpers_by_sum()::578␞Updated '/home/deck/.local/share/dzgui/helpers/ui.py' to sum '05a84408e1d375a38a899b715c38da6e'
2024-03-28 21:15:28,112␞INFO␞/home/deck/Games/dzgui.sh::fetch_helpers_by_sum()::568␞query_v2.py is current
2024-03-28 21:15:28,122␞WARN␞/home/deck/Games/dzgui.sh::fetch_helpers_by_sum()::570␞File '/home/deck/.local/share/dzgui/helpers/funcs' checksum != '80f1740a56e0b81d8c811ef9ac749c36'
2024-03-28 21:15:28,495␞INFO␞/home/deck/Games/dzgui.sh::fetch_helpers_by_sum()::578␞Updated '/home/deck/.local/share/dzgui/helpers/funcs' to sum '80f1740a56e0b81d8c811ef9ac749c36'
2024-03-28 21:15:28,830␞INFO␞/home/deck/Games/dzgui.sh::check_version()::309␞Local branch: 'stable', local version: 5.2.0
2024-03-28 21:15:29,074␞INFO␞/home/deck/Games/dzgui.sh::check_version()::318␞Local version is same as upstream
2024-03-28 21:15:33,452␞INFO␞/home/deck/Games/dzgui.sh::check_map_count()::406␞Prompting user for sudo escalation
2024-03-28 21:15:47,201␞DEBUG␞/home/deck/Games/dzgui.sh::check_map_count()::413␞Old map count is 
2024-03-28 21:15:53,696␞DEBUG␞/home/deck/Games/dzgui.sh::check_map_count()::418␞Updated map count to 1048576
2024-03-28 21:15:53,816␞INFO␞/home/deck/Games/dzgui.sh::steam_deps()::459␞Preferred client set to 'steam'
2024-03-28 21:15:54,353␞INFO␞/home/deck/Games/dzgui.sh::print_config_vals()::122␞Read key 'branch': 'stable'
2024-03-28 21:15:54,354␞INFO␞/home/deck/Games/dzgui.sh::print_config_vals()::122␞Read key 'seen_news': ''
2024-03-28 21:15:54,356␞INFO␞/home/deck/Games/dzgui.sh::print_config_vals()::122␞Read key 'name': 'Jotti'
2024-03-28 21:15:54,357␞INFO␞/home/deck/Games/dzgui.sh::print_config_vals()::122␞Read key 'fav_server': '172.111.51.159:2302:27016'
2024-03-28 21:15:54,359␞INFO␞/home/deck/Games/dzgui.sh::print_config_vals()::122␞Read key 'fav_label': 'Escape From Chernarus'
2024-03-28 21:15:54,360␞INFO␞/home/deck/Games/dzgui.sh::print_config_vals()::122␞Read key 'auto_install': ''
2024-03-28 21:15:54,361␞INFO␞/home/deck/Games/dzgui.sh::print_config_vals()::122␞Read key 'steam_path': '/home/deck/.local/share/Steam'
2024-03-28 21:15:54,366␞INFO␞/home/deck/Games/dzgui.sh::print_config_vals()::122␞Read key 'default_steam_path': '/home/deck/.local/share/Steam'
2024-03-28 21:15:54,370␞INFO␞/home/deck/Games/dzgui.sh::print_config_vals()::122␞Read key 'preferred_client': 'steam'
2024-03-28 21:15:54,372␞WARN␞/home/deck/Games/dzgui.sh::print_config_vals()::125␞No IPs in saved server list
2024-03-28 21:15:54,619␞INFO␞ui.py::main::1799␞Spawned UI from DZGUI setup process
2024-03-28 21:15:54,642␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_keypress for <__main__.TreeView object at 0x7feb5ff9d8c0 (__main__+TreeView at 0x55c712bec8d0)>
2024-03-28 21:15:54,664␞INFO␞ui.py::call_out::271␞Context 'Generic' calling subprocess 'query_config' with args '['debug']'
2024-03-28 21:15:54,673␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::main()::1386␞Received request from UI constructor with params ["query_config", "debug"]
2024-03-28 21:15:54,674␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_map_changed for <Gtk.ComboBox object at 0x7feb5cd6a680 (GtkComboBox at 0x55c712d22e80)>
2024-03-28 21:15:54,675␞INFO␞ui.py::call_out::271␞Context 'Main menu' calling subprocess 'query_config' with args '['']'
2024-03-28 21:15:54,684␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::main()::1386␞Received request from UI constructor with params ["query_config", ""]
2024-03-28 21:15:54,703␞INFO␞ui.py::_on_tree_selection_changed::806␞Tree selection for context 'Main menu' changed to 'Server browser'
2024-03-28 21:15:58,559␞INFO␞ui.py::_on_tree_selection_changed::806␞Tree selection for context 'Main menu' changed to 'My saved servers'
2024-03-28 21:15:59,435␞INFO␞ui.py::_on_row_activated::1142␞User selected 'My saved servers' for the context 'Main menu'
2024-03-28 21:15:59,435␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd672c0 (GtkCheckButton at 0x55c712d8fd00)>
2024-03-28 21:15:59,435␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5fef59c0 (GtkCheckButton at 0x55c712d92a10)>
2024-03-28 21:15:59,435␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd67ec0 (GtkCheckButton at 0x55c712d946e0)>
2024-03-28 21:15:59,435␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68080 (GtkCheckButton at 0x55c712cdd660)>
2024-03-28 21:15:59,435␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68180 (GtkCheckButton at 0x55c712cdf160)>
2024-03-28 21:15:59,435␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68380 (GtkCheckButton at 0x55c712ce0c80)>
2024-03-28 21:15:59,435␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68340 (GtkCheckButton at 0x55c712ce37c0)>
2024-03-28 21:15:59,435␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68580 (GtkCheckButton at 0x55c712ce5250)>
2024-03-28 21:15:59,435␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd685c0 (GtkCheckButton at 0x55c712ce6d40)>
2024-03-28 21:15:59,435␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:15:59,438␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd672c0 (GtkCheckButton at 0x55c712d8fd00)>
2024-03-28 21:15:59,439␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5fef59c0 (GtkCheckButton at 0x55c712d92a10)>
2024-03-28 21:15:59,439␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd67ec0 (GtkCheckButton at 0x55c712d946e0)>
2024-03-28 21:15:59,439␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68080 (GtkCheckButton at 0x55c712cdd660)>
2024-03-28 21:15:59,439␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68180 (GtkCheckButton at 0x55c712cdf160)>
2024-03-28 21:15:59,439␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68380 (GtkCheckButton at 0x55c712ce0c80)>
2024-03-28 21:15:59,439␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68340 (GtkCheckButton at 0x55c712ce37c0)>
2024-03-28 21:15:59,439␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68580 (GtkCheckButton at 0x55c712ce5250)>
2024-03-28 21:15:59,439␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd685c0 (GtkCheckButton at 0x55c712ce6d40)>
2024-03-28 21:15:59,439␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_keypress for <__main__.TreeView object at 0x7feb5ff9d8c0 (__main__+TreeView at 0x55c712bec8d0)>
2024-03-28 21:15:59,446␞INFO␞ui.py::call_out::271␞Context 'Name (My saved servers)' calling subprocess 'dump_servers' with args '['My saved servers', '1PP', '3PP', 'Day', 'Night', 'Low pop', 'Empty', 'Full', 'Non-ASCII', 'Duplicate', 'Keyword␞', 'Map=All maps']'
2024-03-28 21:15:59,447␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_map_changed for <Gtk.ComboBox object at 0x7feb5cd6a680 (GtkComboBox at 0x55c712d22e80)>
2024-03-28 21:15:59,447␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:15:59,455␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::main()::1386␞Received request from UI constructor with params ["dump_servers", "My saved servers", "1PP", "3PP", "Day", "Night", "Low pop", "Empty", "Full", "Non-ASCII", "Duplicate", "Keyword␞", "Map=All maps"]
2024-03-28 21:15:59,459␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::dump_servers()::572␞Server context is 'My saved servers', reading from file '/home/deck/.cache/dzgui/dzg.my_servers'
2024-03-28 21:15:59,484␞WARN␞/home/deck/.local/share/dzgui/helpers/funcs::filter_servers()::483␞Filter result is empty
2024-03-28 21:15:59,485␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:15:59,485␞INFO␞ui.py::call_out::271␞Context 'Name (My saved servers)' calling subprocess 'get_unique_maps' with args '['My saved servers']'
2024-03-28 21:15:59,493␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::main()::1386␞Received request from UI constructor with params ["get_unique_maps", "My saved servers"]
2024-03-28 21:15:59,495␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::get_unique_maps()::364␞Map filter context is: 'My saved servers', using cached file at '/home/deck/.cache/dzgui/dzg.my_servers'
2024-03-28 21:15:59,497␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:04,953␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:04,953␞INFO␞ui.py::_on_selection_button_clicked::575␞User clicked 'Main menu'
2024-03-28 21:16:04,953␞INFO␞ui.py::_update_single_column::539␞Returning from multi-column view to monocolumn view for the context 'Main menu'
2024-03-28 21:16:04,953␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_map_changed for <Gtk.ComboBox object at 0x7feb5cd6a680 (GtkComboBox at 0x55c712d22e80)>
2024-03-28 21:16:04,955␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:13,718␞INFO␞ui.py::_on_row_activated::1142␞User selected 'Server browser' for the context 'Main menu'
2024-03-28 21:16:13,718␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd672c0 (GtkCheckButton at 0x55c712d8fd00)>
2024-03-28 21:16:13,718␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5fef59c0 (GtkCheckButton at 0x55c712d92a10)>
2024-03-28 21:16:13,718␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd67ec0 (GtkCheckButton at 0x55c712d946e0)>
2024-03-28 21:16:13,718␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68080 (GtkCheckButton at 0x55c712cdd660)>
2024-03-28 21:16:13,718␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68180 (GtkCheckButton at 0x55c712cdf160)>
2024-03-28 21:16:13,718␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68380 (GtkCheckButton at 0x55c712ce0c80)>
2024-03-28 21:16:13,718␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68340 (GtkCheckButton at 0x55c712ce37c0)>
2024-03-28 21:16:13,718␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68580 (GtkCheckButton at 0x55c712ce5250)>
2024-03-28 21:16:13,718␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd685c0 (GtkCheckButton at 0x55c712ce6d40)>
2024-03-28 21:16:13,718␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:13,724␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd672c0 (GtkCheckButton at 0x55c712d8fd00)>
2024-03-28 21:16:13,724␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5fef59c0 (GtkCheckButton at 0x55c712d92a10)>
2024-03-28 21:16:13,724␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd67ec0 (GtkCheckButton at 0x55c712d946e0)>
2024-03-28 21:16:13,724␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68080 (GtkCheckButton at 0x55c712cdd660)>
2024-03-28 21:16:13,724␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68180 (GtkCheckButton at 0x55c712cdf160)>
2024-03-28 21:16:13,724␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68380 (GtkCheckButton at 0x55c712ce0c80)>
2024-03-28 21:16:13,724␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68340 (GtkCheckButton at 0x55c712ce37c0)>
2024-03-28 21:16:13,724␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd68580 (GtkCheckButton at 0x55c712ce5250)>
2024-03-28 21:16:13,724␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_check_toggle for <Gtk.CheckButton object at 0x7feb5cd685c0 (GtkCheckButton at 0x55c712ce6d40)>
2024-03-28 21:16:13,724␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_keypress for <__main__.TreeView object at 0x7feb5ff9d8c0 (__main__+TreeView at 0x55c712bec8d0)>
2024-03-28 21:16:13,732␞INFO␞ui.py::call_out::271␞Context 'Name (Server browser)' calling subprocess 'dump_servers' with args '['Server browser', '1PP', '3PP', 'Day', 'Night', 'Low pop', 'Keyword␞', 'Map=All maps']'
2024-03-28 21:16:13,733␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_map_changed for <Gtk.ComboBox object at 0x7feb5cd6a680 (GtkComboBox at 0x55c712d22e80)>
2024-03-28 21:16:13,733␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:13,750␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::main()::1386␞Received request from UI constructor with params ["dump_servers", "Server browser", "1PP", "3PP", "Day", "Night", "Low pop", "Keyword␞", "Map=All maps"]
2024-03-28 21:16:13,861␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::dump_servers()::572␞Server context is 'Server browser', reading from file '/home/deck/.cache/dzgui/dzg.servers'
2024-03-28 21:16:13,943␞WARN␞/home/deck/.local/share/dzgui/helpers/funcs::filter_servers()::483␞Filter result is empty
2024-03-28 21:16:13,946␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:13,946␞INFO␞ui.py::call_out::271␞Context 'Name (Server browser)' calling subprocess 'get_unique_maps' with args '['Server browser']'
2024-03-28 21:16:13,962␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::main()::1386␞Received request from UI constructor with params ["get_unique_maps", "Server browser"]
2024-03-28 21:16:13,968␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::get_unique_maps()::364␞Map filter context is: 'Server browser', using cached file at '/home/deck/.cache/dzgui/dzg.servers'
2024-03-28 21:16:13,974␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:19,063␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:19,078␞INFO␞ui.py::_on_selection_button_clicked::575␞User clicked 'Options'
2024-03-28 21:16:19,078␞INFO␞ui.py::_update_single_column::539␞Returning from multi-column view to monocolumn view for the context 'Options'
2024-03-28 21:16:19,078␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_map_changed for <Gtk.ComboBox object at 0x7feb5cd6a680 (GtkComboBox at 0x55c712d22e80)>
2024-03-28 21:16:19,079␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:25,162␞INFO␞ui.py::_on_tree_selection_changed::806␞Tree selection for context 'Options' changed to 'Change Steam API key'
2024-03-28 21:16:25,482␞INFO␞ui.py::_on_row_activated::1142␞User selected 'Change Steam API key' for the context 'Options'
2024-03-28 21:16:25,483␞INFO␞ui.py::process_tree_option::344␞Parsing tree option 'Change Steam API key' for the context 'Options'
2024-03-28 21:16:31,562␞INFO␞ui.py::process_tree_option::428␞User aborted entry dialog
2024-03-28 21:16:35,582␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:35,582␞INFO␞ui.py::_on_selection_button_clicked::575␞User clicked 'Help'
2024-03-28 21:16:35,583␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:37,379␞INFO␞ui.py::_on_tree_selection_changed::806␞Tree selection for context 'Help' changed to 'Show debug log'
2024-03-28 21:16:38,794␞INFO␞ui.py::_on_row_activated::1142␞User selected 'Show debug log' for the context 'Help'
2024-03-28 21:16:38,794␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:16:38,796␞INFO␞ui.py::call_out::271␞Context 'Timestamp' calling subprocess 'show_log' with args '[]'
2024-03-28 21:16:38,813␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::main()::1386␞Received request from UI constructor with params ["show_log"]
2024-03-28 21:16:38,823␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:17:04,750␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:17:04,750␞INFO␞ui.py::_on_selection_button_clicked::575␞User clicked 'Help'
2024-03-28 21:17:04,750␞INFO␞ui.py::_update_single_column::539␞Returning from multi-column view to monocolumn view for the context 'Help'
2024-03-28 21:17:04,751␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_map_changed for <Gtk.ComboBox object at 0x7feb5cd6a680 (GtkComboBox at 0x55c712d22e80)>
2024-03-28 21:17:04,753␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:17:07,171␞INFO␞ui.py::_on_tree_selection_changed::806␞Tree selection for context 'Help' changed to 'Show debug log'
2024-03-28 21:17:07,526␞INFO␞ui.py::_on_row_activated::1142␞User selected 'Show debug log' for the context 'Help'
2024-03-28 21:17:07,526␞DEBUG␞ui.py::toggle_signal::1613␞Blocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>
2024-03-28 21:17:07,528␞INFO␞ui.py::call_out::271␞Context 'Timestamp' calling subprocess 'show_log' with args '[]'
2024-03-28 21:17:07,541␞INFO␞/home/deck/.local/share/dzgui/helpers/funcs::main()::1386␞Received request from UI constructor with params ["show_log"]
2024-03-28 21:17:07,552␞DEBUG␞ui.py::toggle_signal::1610␞Unblocking _on_tree_selection_changed for <Gtk.TreeSelection object at 0x7feb5cd66740 (GtkTreeSelection at 0x55c712beca00)>

**Comment by aclist** [comment] 2024-03-29 02:25
For starters, you don't have any saved IPs in your saved servers list. The file `/home/deck/.config/dztui/dztuirc` should have a field called `ip_list` consisting of the IPs you saved. According to DZGUI, this field is empty, because you did not save any servers. To save servers, you must use `Manage > Add server by IP` or `Manage > Add server by ID`, or right-click a server in the server browser and select to add it to your saved servers.

The My Servers table is not going to have any content in it until you add servers to be saved.

As for the server browser itself, it is also coming back empty. As a start, remove the files `/home/deck/.cache/dzgui/dzg.servers` and `/home/deck/.cache/dzgui/dzg.my_servers` if present, and allow them to be repopulated.

Secondly, update your API key and make sure it is exactly corrected as indicated in Steam. If the server list is coming back empty, you may be using the wrong API key.

Thirdly,  invoke the following set of commands from a terminal and report the output in a subsequent reply here:

```
source $HOME/.config/dztui/dztuirc
curl -ILs "https://api.steampowered.com/IGameServersService/GetServerList/v1/?filter=\appid\221100&limit=10&key=$steam_api" | grep -E "^HTTP"
```

Steam may have intermittent connectivity issues on or around Tuesdays/Wednesdays, but also check your network topology if you think there is some reason your device can't communicate with Steam correctly.

So far, I cannot reproduce this bug, leading me to think your API key is malformed, but I am not discounting the possibility that something else is blocking the server results from filtering.

As an another alternative, check to make sure you don't have conflicting or disabled server filters (e.g., if you turned off both Day and Night servers, there will be zero hits). It looks like you have the default filters on, but check to make sure you aren't artifically restricting the results from being shown.

If the file `dzg.servers` is completely empty, it points to a problem that will require additional tests and troubleshooting to resolve.

**Comment by aclist** [comment] 2024-03-31 02:08
Closed as resolved per comments from user on other channel

**Closed by aclist** 2024-03-31 02:08 UTC

**Comment by Jott007** [comment] 2024-03-31 03:38
Good looking out bro, appreciate the feedback. I did figure it out and it
was my API key. Thanks again.

**Comment by aclist** [comment] 2024-03-31 08:08
Glad you got it working. Let me know if you run into other issues in the future.
