### ISSUE TITLE
New issue on steam deck

### ISSUE THREAD

**Issue by GKourp** [aclist/dztui#79] opened 2023-09-24 07:26 UTC
When launching from desktop mode or regular steam deck mode, I receive the warning of steam console taking focus and needing focus for mod receipt. I allow it to run after the warning and after a certain point and it runs for what seems to be hours. I've run it a few times at this point.

**Comment by aclist** [comment] 2023-09-24 09:04
Thanks for the report. Most likely there has been some change to the Steam client that makes the old method of finding and focusing the process no longer viable.

Have you enabled auto mod downloads, or is this using the manual mode (subscribe to each mod one at a time)? Based on your message (references to the console), it sounds like you enabled auto mod downloads. 

What version of DZGUI are you running?

**Comment by GKourp** [comment] 2023-09-25 22:31
Yes I have auto download enabled, and I am on 3.3.13.

**Comment by aclist** [comment] 2023-09-26 21:28
This issue is being investigated on a Steam Deck test bench. Note that the auto download mod is an experimental feature. 

For the time being, I suggest enabling manual downloading and seeing if this clears the blockage.

Once the auto mode is tested against the new version of the Steam client, I will update this ticket with my findings and a fix.

**Comment by GKourp** [comment] 2023-10-06 15:58
So I tried to change the setting to load mods manually and it says  ,"This feature is not supported on the steam deck." Any idea?

**Comment by aclist** [comment] 2023-10-07 07:02
Thanks for your patience. I had to test a number of parameters to get to the root of the issue. A general summary follows:

1. You stated that you were using the Auto Download feature, but this is not in fact supported on Steam Deck. I interpreted this to mean that you were in fact using the (Semi) Manual Download feature, which opens the mod pages in Steam and prompts you to subscribe to them.
2. I verified that on SteamOS 3.4.11 Stable, the Steam client (Desktop Mode) inherits an upstream bug from here: https://github.com/ValveSoftware/steam-for-linux/issues/9598. Steam uses the Electron framework to load pages of content via a web browser. In the aforementioned bug, some pages of the client (Library, Store, etc.) will fail to load and show a "black screen" until the user navigates back and forth to multiple pages. This currently affects a number of different Linux distributions and the bug is not totally resolved. It relates to changes made in the Steam client.
3. When launching DZGUI on Desktop Mode and attempting to connect to a server requiring mods, it requests Steam to load the Workshop pages for the mods needed and shows a progress dialog. Because of the bug above, the Workshop pages "load" but do not update with any content, so the dialog is waiting endlessly for the user to tap the button to Subscribe to a mod, but they never can, because Steam isn't loading the page.
4. I resolved this by opening the Steam client and navigating multiple times between the Library and Store tabs until the Store page started loading. After this point, when DZGUI requests Steam to load mod pages, they will show up correctly and let you advance through the process.

There is currently no reliable fix for this on Steam's end, and it's not something being caused by DZGUI. I recommend refreshing Steam and loading all of the Store/Library/Profile tabs before running DZGUI to make sure Steam is loading content properly. I would also recommend opting into the Beta branch of SteamOS to see if this resolves the issue.

**Comment by aclist** [comment] 2023-10-07 07:12
As an additional data point, the issue seems to go away if you make sure Steam is launched first before running DZGUI. If Steam is not open on Desktop Mode and DZGUI has to request that Steam both launch and open the desired page, the black screen occurs. If you instead have Steam already open, the content loads as intended.

I can look into foregrounding the Steam process before requesting Workshop pages. As a test, can you try:

1. Open Steam in Desktop Mode
2. Open DZGUI after this
3. Connect to a new server you don't have the mods for
4. See if Workshop pages load as a black screen or load correctly

The reason force updating local mods worked for you is because it obviated the entire process above, but it still could occur when connecting to a new server, so I want to make sure we resolve this rather than use workarounds.

**Comment by GKourp** [comment] 2023-10-21 22:55
I switched DZGUI to exp mode and it seems to work just fine.

**Comment by aclist** [comment] 2023-10-22 08:44
May I ask what exp mode is?

**Comment by GKourp** [comment] 2023-10-22 15:06
Oh my mistake, its called testing branch. Switched over on Friday and Saturday and both days it worked.

**Comment by aclist** [comment] 2023-10-23 08:06
In general it should work on either branch now, provided Steam was already running before DZG. I'm looking into adding a warning for Steam Deck if Steam isn't running.

**Comment by aclist** [comment] 2023-11-01 16:33
Closing as solved; please reopen if the issue recurs

**Closed by aclist** 2023-11-01 16:33 UTC
