### ISSUE TITLE
Space inserted after name causing repeated kicks from server

### ISSUE THREAD

**Issue by OliveAlpaca** [aclist/dztui#146] opened 2024-08-31 03:07 UTC
The launcher seems to be inserting a space after I input my custom name. This causes me to be instantly kicked from servers.
I deduced this from the following line in the crash logs;

-name=Hannibal Lecter "

Essentially the space after the name but before the " seems to be the issue.

**Comment by aclist** [comment] 2024-08-31 09:43
I see that you opened this issue twice and closed one; I was notified by e-mail about the other one and not this one. I take it that you have not resolved the issue, since you opened two tickets.

When you say the crash logs, are you talking about Proton logs, DayZ logs, or DZGUI logs?

I wasn't able to reproduce the issue here yet (using a name with multiple words in it did not crash the game, and loaded into the server with the full name as intended). 

A couple of questions:

- Are you sure there is no extra space added in the text field?
- Does the crash go away immediately when you use a name consisting of a single word?

What is the explicit error message when you get kicked? You mentioned getting kicked from servers and also crashing: are you simply getting kicked, or is the client crashing, too?

It would also help to know about what DZGUI version you are using, and provide the `DZGUI_DEBUG.log` from `$HOME/.local/state/dzgui/logs`. Thank you.

**Comment by OliveAlpaca** [comment] 2024-09-01 01:24
Apologies for the duplicate, I am truly new around here. I don't believe I mentioned crashing and if I did, I was not crashing. I am ONLY being kicked from the server. I discovered the extra space in the Dayz files. I am 100% sure that I am not inserting a space in the name change field when I apply a name change. Additionally, the server I am a member of requires a character sheet on a secondary website which determines which names can join - and my character names do not have additional spaces at the end. I have spoken to the server management and they are looking into it, although it seems to be an issue with the launcher. 

I was unable to find the logs folder in the path you provided, but I dug around in some sort of config file; I am using DZGUI version 5.3.2. I am a little busy but I will continue to dig around and post any other information I can come up with.

**Comment by OliveAlpaca** [comment] 2024-09-01 01:34
![Screenshot from 2024-08-31 21-33-24](https://github.com/user-attachments/assets/f12581b1-44f0-4220-a608-8df47873de1f)

Attached is a screenshot from the config file, showing that (one of my) character names is correctly missing the trailing space, yet I am still unable to stay connected to the server.

**Comment by aclist** [comment] 2024-09-01 04:42
> Apologies for the duplicate, I am truly new around here. I don't believe I mentioned crashing and if I did, I was not crashing. I am ONLY being kicked from the server.

Not to worry, just making sure we cover all the bases here.

> I am 100% sure that I am not inserting a space in the name change field when I apply a name change.

Thanks for confirming.

> Additionally, the server I am a member of requires a character sheet on a secondary website which determines which names can join - and my character names do not have additional spaces at the end. I have spoken to the server management and they are looking into it, although it seems to be an issue with the launcher.

Alright, this is good information. Disregard the single name test, then.

---
I neglected to mention one detail in my last message: an issue with complex names (first name, surname) has already been patched on the Testing branch for a little while now, and I wrongly assumed you were using the most up to date version. Those changes were being held back from the Stable version until today, because I wanted to finish testing and consolidating some other changes. Sorry for not double-checking which version you were on.

The new version of DZGUI is 5.3.0. When given a prompt to update, accept the change and try testing on your preferred server. You won't have to update your name or config file, as the fix takes place internally. 

I am fairly confident this should resolve your issue, making it a duplicate of #136. If the issue persists, please let me know.

**Comment by aclist** [comment] 2024-09-10 03:58
Closing as resolved by 56a6e7a. Please reopen if this issue recurs.

**Closed by aclist** 2024-09-10 03:58 UTC
