### ISSUE TITLE
[BUG] Unable to connect to local server

### ISSUE THREAD

**Issue by t0m5k1** [aclist/dztui#49] opened 2023-01-07 10:57 UTC
**Info**
DZGUI version: 3.1.7
Mode (normal/debug): Normal
Server ID: N/A Local Server
Linux distribution: arch

I feed the setup both API keys and my normal username (t0m5k1).
Once DZGUI is running I select "Connect by IP", I then feed it the IP of the server I want to connect to: 192.168.0.17, This fails as for some reason it can't get the metadata: 
```[ERROR] 96: Failed to retrieve IP metadata. Check IP or API key and try again.```

**Steps to reproduce the behavior:**
1. Click "Connect to IP"
2. In pop up type in IP of local server
3. Click OK
4. See error: ```[ERROR] 96: Failed to retrieve IP metadata. Check IP or API key and try again.```

**Expected behavior**
DZGUI Should collate the necessary mods and feed to steam the relevant launch parameters to allow dayz to connect to my local server with the required mods just as it would if this was a public server.

**Note:**
I think this is happening because you're using API to connect to a 3rd party source in the hope that this source will give you the list of required mods, I'm certain (not a programmer) All servers once connected to a client provide data that lists the required mods, this is how the normal launcher knows what to setup, what are you doing that is either ignoring this or doesn't know how to parse the info?

**Comment by aclist** [comment] 2023-01-07 11:22
It fails because DZGUI has no internal logic for handing servers on a local network. Unfortunately, only one person besides you has asked for it so far and I don't know anything about running a local DayZ server, so my test surface is effectively zero. There is a preliminary skeleton of code I added as a placeholder for the time when we choose to add local server support, but someone who is a server operator (perhaps you) would have to explicitly define how this process works so that I can implement it, as Bohemia provides scanty information.

I don't think creating a full client and server networking logic is the correct (or viable) approach here. This is merely a kickoff launcher that passes the options to the actual game, not something using a networking protocol. It would be simpler to just explore the local server for its canonical mod list and then feed those parameters into DZGUI. (That's far easier.)

To start, you'd have to explain where the local server stores its mod manifest and if it is in a reliable location and format. Presumably it's got a list of mod IDs or a unified directory where you save mods to. If that's the case, it's fairly trivial to parse the mod parameters. We could have an additional menu category for doing so.

Of course, the above presumes a single user scenario. This would not cover the case of a LAN party, where another PC on the local subnet wants to connect to a server on the main LAN, since we aren't traversing the network per se, but it seems that in scenarios like that, the local server operator (you) could simply provide a mod manifest file that the other users can load into DZGUI.

Local network traversal and client<>server discovery is out of scope here. If that wasn't explained properly in the documentation, I can reword it. To clarify further, passing the local IP to the DayZ client is not a problem, and this should work fine once the launch options are concatenated. Just need a clear and reliable way of exploring the installed mods. I asked a few people who have local servers and none of them was able to articulate where the server keeps its mods, so I haven't pursued this further beyond adding some placeholder code.

**Comment by t0m5k1** [comment] 2023-01-07 13:59
Thanks for the response.

The server doesn't "list" any mods it's using and the only place where this would be is in a .bat file used to start the server.
I think you're taking an overly in depth approach to this. I was not suggesting you use some network protocol nor was I suggesting you start scanning the local network for dayz servers. Just merely stating that the normal dayz launcher manages to ascertain what mods and their versions from the initial response the server provide which contains some metadata, Shame Bohemia don't give much info.

At the end of the day all I'm looking for is a way to connect my dayz client to a server I'm running with the mods I want, the normal launcher can't seem to do this and so far this is the closest and I refuse to install windows just to play a game (not saying you suggested this).
Guess I'll keep endlessly buggering around with the steam url to launch the bloody game even though I have no clue what to do  other than trying different combinations with launch options in the properties but none of them work!

Cheers again

**Comment by aclist** [comment] 2023-01-07 15:49
I still think it's eminently doable and I don't mind leaving this open and taking a crack at it, but there would be various caveats (enumerated below).

As for the methodology, I have to by necessity take an in-depth approach to considering all of the possible ramifications of a feature (hence the LAN party analogy), otherwise you end up with unexpected behavior and pitfalls that could have been avoided by designing defensively and itemizing them in the planning stage. Those scenarios may seem irrelevant, but so, too, did launching a local server at the time. 

The real client uses the A2S protocol to query the server. DZGUI does not communicate with any servers. It doesn't query or talk to any individual server at any point. It just fetches the metadata that is broadcast by all servers to the master server for indexing. (Reasons for that are outlined at the end)

I watched a few videos about local server setup. It seems you copy mod directories prefixed with an @ sign into the server's root directory. I assume you did this? If the mods are properly formed, they should have a `meta.cpp` file inside them that contains the unique ID. 

1. We can parse these IDs in order to build up a manifest of the mods the server is running
2. For one, this could be achieved by having the user provide the path to the local server so that DZGUI can parse the directories*
3. In order to preserve the rest of the logic of the application, it would be best to, after checking the locally installed mods against the server's mods, download any missing mods as usual and follow the standard (generic) DZGUI logic. Even though the mods are technically already on the local server, there's no guarantee the server is even on the same local PC, so we can't just "borrow" those mod files
4. The handoff of launch options to the Steam client at that point should function the same as before. As a test, have you tried manually connecting to your server with no mods installed on it and using the Steam launch parameters to supply the local IP? 

*Assuming it's installed on the same machine. If the server is just on the local network but not on the same PC, then we don't have an easy way of probing the files without talking to the server directly using the A2S protocol. I've avoided implementing this for now, since it is a) a non-trivial undertaking to implement from scratch or b) introduces extra dependencies if we pull in an external library and c) Bohemia changed the challenge-response encoding of server modlists to a complex format that is undocumented. Point C is a big problem that has confounded other projects for some time and is blocking further developments. I would like to implement this at some point, as it would greatly streamline the application to have a native API, but this project does not have the scope or budget to accommodate that right now.

However...we could ship a stripped-down utility solely for the convenience of server operators that you run on the server machine, it spits out a manifest file, and then you load this manifest into DZGUI and it prepares what you need. This would also help with the LAN party scenario as a generic/portable way of connecting.

I think this is a good idea, as it's minimally invasive, puts the responsibility to install the extra utility on the server operator, and is generic enough that it doesn't break the flow of other processes inside DZGUI. And it is not difficult to implement.

**Closed** 2023-02-22 08:49 UTC
